export enum ErrorMessages {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXISTS = 'USER_EXISTS',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_TOKEN = 'INVALID_TOKEN',
  PASSWORD_DID_NOT_MATCHED = 'PASSWORD_DID_NOT_MATCHED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  OTP_DID_NOT_MATCH = 'OTP_DID_NOT_MATCH',
  OTP_EXPIRED = 'OTP_EXPIRED',
  NOT_ALLOWED = 'NOT_ALLOWED',
  OTP_NOT_FOUND = 'OTP_NOT_FOUND',
}
